//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCarrito
    {
        public long Consecutivo { get; set; }
        public long ConsecutivoUsuario { get; set; }
        public long ConsecutivoProducto { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual tProducto tProducto { get; set; }
        public virtual tUsuario tUsuario { get; set; }
    }
}
