//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDetalle
    {
        public long Consecutivo { get; set; }
        public long ConsecutivoMaestro { get; set; }
        public long ConsecutivoProducto { get; set; }
        public int CantidadPagada { get; set; }
        public decimal PrecioUnitarioPagado { get; set; }
        public decimal TotalProducto { get; set; }
    
        public virtual tMaestro tMaestro { get; set; }
        public virtual tProducto tProducto { get; set; }
    }
}
