//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMaestro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tMaestro()
        {
            this.tDetalle = new HashSet<tDetalle>();
        }
    
        public long Consecutivo { get; set; }
        public long ConsecutivoUsuario { get; set; }
        public decimal TotalPagado { get; set; }
        public System.DateTime FechaCompra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tDetalle> tDetalle { get; set; }
        public virtual tUsuario tUsuario { get; set; }
    }
}
